name: Code Quality and Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  HUSKY: 0

permissions:
  contents: write

jobs:
  code-cleanup:
    name: Clean up code - format and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Node.js version from .nvmrc
        id: node-version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - name: Install dependencies
        run: npm i
      - name: Format code
        run: npm run codefix
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatic Code cleanup - format and lint 🧹"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Node.js version from .nvmrc
        id: node-version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - run: npm run typecheck